#ddev-generated
ARG BASE_IMAGE
FROM $BASE_IMAGE
# =========================================
# enable serverside includes in apache
# =========================================
RUN a2enmod include

# =========================================
# install svgo for image optimize
# =========================================
RUN sudo npm install -g svgo
RUN sudo ln -sf /usr/local/bin/svgo /usr/bin/svgo
