#!/bin/bash

## #ddev-generated
## Description: Initialize craft with seed db
## Usage: init-craft
## Example: ddev init-craft
## ExecRaw: true
## HostWorkingDir: true

# check to see if DDEV_NONINTERACTIVE=true exit early
if [ "$DDEV_NONINTERACTIVE" = "true" ]; then
  echo "Not trying to init Craft because DDEV_NONINTERACTIVE=true"
  exit 0
fi

# Check to see if we need to seed the db
if ddev craft install/check; then
  ddev composer install
else
  echo "Craft not installed, importing seed db..."
  # post import-db hook will automatically run composer install
  ddev import-db -f=seed.sql.gz
fi

echo "installing node dependencies..."
ddev pnpm install

echo "building front-end..."
ddev pnpm build
