#!/bin/bash
#ddev-generated

target=(
  [sshUser]=
  [sshHost]=
  [sshPort]=
  [mysqlHost]=
  [mysqlPort]=
  [mysqlUser]=
  [mysqlPass]=
  [mysqlDatabase]=
  # ignore from data dump
  [ignoredDbTablesPattern]=
  # ignore from schema and data dump
  [fullyIgnoredDbTablesPattern]=
)
